#!/bin/bash
########################################################################
# Fedora Updater (fu): lightweight Fedora « distribution »
#
# Copyright (C) 2018-2025 Christophe Delord
# https://codeberg.org/cdsoft/fu
#
# This file is part of Fedora Updater (FU)
#
# FU is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# FU is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with FU.  If not, see <http://www.gnu.org/licenses/>.
########################################################################

export PREFIX=~/.local

( hash git && hash gcc && hash g++) 2>/dev/null || sudo dnf install git gcc gcc-c++

[ -x $PREFIX/bin/ninja ] || (
    NINJA_URL="https://codeberg.org/cdsoft/ninja-builder"
    TMP=$(mktemp -d)
    git clone $NINJA_URL "$TMP"
    cd "$TMP" || exit
    ./ninja-builder.sh gcc install
    rm -rf "$TMP"
)

[ -x $PREFIX/bin/luax ] || (
    LUAX_URL="https://codeberg.org/cdsoft/luax"
    TMP=$(mktemp -d)
    git clone $LUAX_URL "$TMP"
    cd "$TMP" || exit
    ./bootstrap.sh gcc small
    $PREFIX/bin/ninja install
    rm -rf "$TMP"
)

eval "$("$PREFIX/bin/luax" env)"
$PREFIX/bin/luax "$(dirname "$(realpath "$0")")/fu.lua" "$@"
